// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type User struct {
	ID        int64     `json:"id"`
	Fistname  string    `json:"fistname"`
	Lastname  int64     `json:"lastname"`
	Email     string    `json:"email"`
	Phno      string    `json:"phno"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
